import type { Property } from './types';

export const propertiesData: Property[] = [
  {
    id: 1,
    name: 'Hacienda Santorini',
    location: 'Playa del Carmen, Quintana Roo',
    type: 'Hacienda',
    price: 4500000,
    minInvestment: 300,
    invested: 0,
    ownedShares: 0,
    totalShares: 100,
    image: 'hacienda-santorini',
    dailyReturn: 0.10,
  },
  {
    id: 2,
    name: 'Casa Monaco',
    location: 'Monterrey, Nuevo León',
    type: 'Casa',
    price: 3800000,
    minInvestment: 500,
    invested: 0,
    ownedShares: 0,
    totalShares: 100,
    image: 'casa-monaco',
    dailyReturn: 0.10,
  },
  {
    id: 3,
    name: 'Residencia Ejecutiva',
    location: 'Santa Fe, Ciudad de México',
    type: 'Residencia',
    price: 6200000,
    minInvestment: 700,
    invested: 0,
    ownedShares: 0,
    totalShares: 100,
    image: 'residencia-ejecutiva',
    dailyReturn: 0.10,
  },
  {
    id: 4,
    name: 'Loft Esmeralda',
    location: 'Polanco, Ciudad de México',
    type: 'Loft',
    price: 5500000,
    minInvestment: 1000,
    invested: 0,
    ownedShares: 0,
    totalShares: 100,
    image: 'loft-esmeralda',
    dailyReturn: 0.10,
  }
];
